### PR TITLE
Fix for pagination issue on Dektop App

### PR DESCRIPTION
**Pull request by nishantswarup**
Rebuild App: Pagination is not working properly on desktop app #7

### CODE REVIEW

**Comment by rajmbcoderx** [comment]
Looks good

**Comment by kumarsudhish** [comment]
Verified this issue on latest Master build by pulling up the code and building it.
And it looks good, verified by 140 files.

image
image
image
image

Hence marking this as Done.

**Comment by kumarsudhish** [comment]
Verified this issue on latest v.01.4 prod version and it working fine.
hence marking this as Closed.

**Comment by kumarsudhish** [comment]
Verified this issue on latest v.01.4 prod version and it working fine.
hence marking this as Closed.

**Pull request merged**
